#include <iostream>
#include <ncurses.h>
#include "syntax_highlighter.l" // Include the lexer header generated by Flex

int main() {
    // Initialize ncurses
    initscr();
    start_color();
    // Initialize color pairs
    init_pair(1, COLOR_RED, COLOR_BLACK);
    init_pair(2, COLOR_GREEN, COLOR_BLACK);
    init_pair(3, COLOR_YELLOW, COLOR_BLACK);
    init_pair(4, COLOR_BLUE, COLOR_BLACK);
    init_pair(5, COLOR_MAGENTA, COLOR_BLACK);

    MyLexer lexer; // Create an instance of your lexer
    lexer.yylex(); // Call yylex() on the lexer instance

    // End ncurses
    endwin();
    return 0;
}
